# yaml-language-server: $schema=https://raw.githubusercontent.com/inpyjamas/schemas/main/render.com.json
# https://render.com/docs/yaml-spec

services:
  - name: surabayajs-shortlinks
    type: web
    env: static
    staticPublishPath: .
    domains:
      - link.surabayajs.org
      - subjs.in
    headers:
      - path: /*
        name: Cache-Control
        value: public, s-maxage=1, stale-while-revalidate=59
    routes:
      - type: redirect
        source: /
        destination: https://surabayajs.org
      - type: redirect
        source: /discord
        destination: https://discord.gg/kx3qp5S
      - type: redirect
        source: /kritiksaran
        destination: https://airtable.com/shrQhziBrtEmaBFaT
      - type: redirect
        source: /lokasi
        destination: https://www.google.com/maps/place/Cleo+Business+Hotel+Jemursari/@-7.3194129,112.7479151,19.69z/data=!4m8!3m7!1s0x2dd7fb105538cc6b:0x7358c1ea255053fe!5m2!4m1!1i2!8m2!3d-7.3192645!4d112.7479993
      - type: redirect
        source: /meetup16
        destination: https://youtu.be/xrFBvOYO_WY
      - type: redirect
        source: /meetup18
        destination: https://www.eventbrite.com/e/meetup-18-what-you-need-to-care-about-vim-and-backend-service-tickets-535895867967
      - type: redirect
        source: /workshop1
        destination: https://www.eventbrite.com/e/chapter-1-javascript-101-tickets-383864788917
      - type: redirect
        source: /feedback
        destination: https://forms.gle/FpPwUT4JMnzNwxNp9
      - type: redirect
        source: /vscode
        destination: https://marketplace.visualstudio.com/items?itemName=surabayajs.surabayajs-extension-pack
      - type: redirect
        source: /vscode-json
        destination: https://raw.githubusercontent.com/surabayajs/surabayajs-extension-pack/master/package.json
